# Generated by Django 4.2.6 on 2023-10-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0004_photo_file"),
        ("users", "0002_alter_user_avatar_alter_user_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="favs",
            field=models.ManyToManyField(
                blank=True, related_name="favs", to="rooms.room"
            ),
        ),
    ]
